/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-01-14 05:08:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"generator\" content=\"Mtopobirise v4.3.5, mobirise.com\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"shortcut icon\" href=\"assets/images/icon1-128x128.png\" type=\"image/x-icon\">\n");
      out.write("        <meta name=\"description\" content=\"Web Page Builder Description\">\n");
      out.write("        <title>Topics</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/web/assets/mobirise-icons/mobirise-icons.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/tether/tether.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap-grid.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap-reboot.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/dropdown/css/style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/theme/css/style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/mobirise/css/mbr-additional.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <section class=\"menu cid-qDGKCD9SPl\" once=\"menu\" id=\"menu1-j\" data-rv-view=\"137\">\n");
      out.write("            <nav class=\"navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm\">\n");
      out.write("                <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <div class=\"hamburger\">\n");
      out.write("                        <span></span>\n");
      out.write("                        <span></span>\n");
      out.write("                        <span></span>\n");
      out.write("                        <span></span>\n");
      out.write("                    </div>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"menu-logo\">\n");
      out.write("                    <div class=\"navbar-brand\">\n");
      out.write("\n");
      out.write("                        <span class=\"navbar-caption-wrap\"><a class=\"navbar-caption text-white display-4\" >\n");
      out.write("                                THE FORUM</a></span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                    <ul class=\"navbar-nav nav-dropdown nav-right\" data-app-modern-menu=\"true\"><li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link link text-white display-4\" href=\"update.jsp\">\n");
      out.write("                                <span class=\"mbri-home mbr-iconfont mbr-iconfont-btn\"></span>&nbsp;Update Details</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link link text-white display-4\" href=\"logout_redirect.jsp\"><span class=\"mbri-users mbr-iconfont mbr-iconfont-btn\"></span>\n");
      out.write("                                Sign Out &nbsp;</a>\n");
      out.write("                        </li></ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <section class=\"mbr-section article content11 cid-qDH9uhaflM\" id=\"content11-v\" data-rv-view=\"35\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"inner-container\" style=\"width: 100%;\">\n");
      out.write("                    <hr class=\"line\" style=\"width: 25%;\">\n");
      out.write("                    <div class=\"section-text align-center mbr-fonts-style display-5\">\n");
      out.write("                        <p>Topics</p> \n");
      out.write("                    </div>\n");
      out.write("                    <hr class=\"line\" style=\"width: 25%;\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"features4 cid-qDGQkJnlNN mbr-fullscreen mbr-parallax-background\" id=\"features4-t\" data-rv-view=\"139\">\n");
      out.write("\n");
      out.write("            <div class=\"container\">\n");
      out.write("\n");
      out.write("                <div class=\"media-container-row\">\n");
      out.write("                    <form action=\"\" method=\"post\">\n");
      out.write("                        <div class=\"card p-3 col-12 col-md-6 col-lg-4\">\n");
      out.write("                            <div class=\"card-wrapper media-container-row\">\n");
      out.write("                                <div class=\"card-box\">       \n");
      out.write("                                    <h4 class=\"card-title pb-3 mbr-fonts-style display-7\">\n");
      out.write("\n");
      out.write("                                    </h4>\n");
      out.write("                                    <p class=\"mbr-text mbr-fonts-style display-7\">\n");
      out.write("                                    <p>topic name</p>\n");
      out.write("                                    <p> title</p>\n");
      out.write("                                    <p>description</p>\n");
      out.write("\n");
      out.write("                                    </p>\n");
      out.write("                                    <button href=\"\" type=\"submit\" class=\"btn btn-form btn-dark display-4\">View</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"assets/web/assets/jquery/jquery.min.js\"></script>\n");
      out.write("        <script src=\"assets/popper/popper.min.js\"></script>\n");
      out.write("        <script src=\"assets/tether/tether.min.js\"></script>\n");
      out.write("        <script src=\"assets/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"assets/smooth-scroll/smooth-scroll.js\"></script>\n");
      out.write("        <script src=\"assets/dropdown/js/script.min.js\"></script>\n");
      out.write("        <script src=\"assets/touch-swipe/jquery.touch-swipe.min.js\"></script>\n");
      out.write("        <script src=\"assets/jarallax/jarallax.min.js\"></script>\n");
      out.write("        <script src=\"assets/theme/js/script.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
