/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-06-19 13:59:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <!-- Required meta tags -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("   \n");
      out.write("    <!-- Bootstrap CSS <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css\" integrity=\"sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy\" crossorigin=\"anonymous\"> -->\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css\" integrity=\"sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy\" crossorigin=\"anonymous\">\n");
      out.write("      \n");
      out.write("    <title>Home | Forum</title>\n");
      out.write("    \n");
      out.write("     <link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\">\n");
      out.write("     <!-- CSS -->\n");
      out.write("    <style name=\"text/css\">\n");
      out.write("\t\t\t*{\n");
      out.write("\t\t\t\tmargin:0;\n");
      out.write("\t\t\t\tpadding:0;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\thtml{\n");
      out.write("\t\t\t\tmin-height:100%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\tbody{\n");
      out.write("\t\t\t\tbackground-image: url(\"mountains.jpg\");\n");
      out.write("\t\t\t\tbackground-repeat: no-repeat;\n");
      out.write("\t\t\t\tbackground-size: cover;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t#center{\n");
      out.write("\t\t\t\ttext-align:center;\n");
      out.write("\t\t\t\tpadding:10px;\n");
      out.write("\t\t\t\twidth:500px;\n");
      out.write("\t\t\t\theight:170px;\n");
      out.write("\t\t\t\tborder-radius:40px;\n");
      out.write("\t\t\t\tbackground-color:white;\n");
      out.write("\t\t\t\tposition:absolute;\n");
      out.write("\t\t\t\ttop:50%;\n");
      out.write("\t\t\t\tleft:50%;\n");
      out.write("\t\t\t\tmargin-right:-50%;\n");
      out.write("\t\t\t\ttransform: translate(-50%, -50%);\n");
      out.write("\t\t\t\topacity:0.50;\n");
      out.write("\t\t\t\tfont-family:Lobster, cursive;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t#title{\n");
      out.write("\t\t\t\tfont-size:32px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t#button{\n");
      out.write("\t\t\t\tborder-radius:10px;\n");
      out.write("\t\t\t\tbackground-color:#ffcca2;\n");
      out.write("\t\t\t\tfont-family:Lobster, cursive;\n");
      out.write("\t\t\t\tfont-size:18px;\n");
      out.write("\t\t\t\tbox-shadow:2px 2px grey;\n");
      out.write("\t\t\t\tpadding:5px;\n");
      out.write("\t\t\t}\n");
      out.write("                        \n");
      out.write("                        h1{\n");
      out.write("                             font-family:Lobster, cursive;\n");
      out.write("                        }\n");
      out.write("                        .blocks{\n");
      out.write("                            padding: 10px;\n");
      out.write("                            margin: 10px;\n");
      out.write("                            background-color: cornsilk;\n");
      out.write("                            border-radius: 10px;\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                       \n");
      out.write("\t\t\n");
      out.write("\t\t</style>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("      <!-- BOOTSTRAP NAVBAR -->\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">FORUM</a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"home.jsp\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link\" href=\"updateProfile.jsp\">Update Profile</a>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link \" href=\"addTopic.jsp\">Add Topic</a>\n");
      out.write("      </li>\n");
      out.write("       <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link \" href=\"login.jsp\">Log Out</a>\n");
      out.write("      </li>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("    ");

    try {
	client.ForumWebService_Service service = new client.ForumWebService_Service();
	client.ForumWebService port = service.getForumWebServicePort();
	 // TODO initialize WS operation arguments here
	java.lang.String email = (String) request.getSession().getAttribute("email");
	// TODO process result here
        String uid =port.getID(email);
        request.getSession().setAttribute("userID", uid);
        
	java.lang.String result = port.getName(email);
        //DISPLAYS A WELCOME MESSAGE TO USER.
        out.println("<br>");
        out.println("<h1 style= color:white;>Welcome " + result + "!</h1>");
        
        service = new client.ForumWebService_Service();
	port = service.getForumWebServicePort();
	// TODO process result here
	java.util.List<java.lang.Object> topics = port.getTopics();
        //FOR-LOOP FOR THE DISPLAYING OF TOPICS
        for(int i = 0;i < topics.size(); i++){
            String[] temp = (topics.get(i) + "").split(".#/");
    
      out.write("\n");
      out.write("    <div class=\"blocks\">\n");
      out.write("        <div style=\"margin: 20px;\">");
out.println("Title: <a href=\"viewTopic.jsp?Id="  + temp[0] + "\">" + temp[1] +"</a><br>Description: " + temp[2] + "<br>Created By: " + temp[3]); 
      out.write("</div>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    ");

        }
        
    } catch (Exception ex) {	
        out.println("Error: " + ex);
    }
    
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Optional JavaScript -->\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js\" integrity=\"sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
