/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-07 09:10:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import unit6.*;

public final class editDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

            String name;
        
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      client.DatabaseConnectClient connection = null;
      synchronized (session) {
        connection = (client.DatabaseConnectClient) _jspx_page_context.getAttribute("connection", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (connection == null){
          connection = new client.DatabaseConnectClient();
          _jspx_page_context.setAttribute("connection", connection, javax.servlet.jsp.PageContext.SESSION_SCOPE);
          out.write("\n");
          out.write("    ");
          out.write('\n');
        }
      }
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Topic Wiz Edit Details</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"editCSS.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"container\" >\n");
      out.write("            ");

                String tempName = (String) session.getAttribute("user");
                if (tempName != null && !tempName.equals("")) {
                    name = tempName;
                } else {
                    response.sendRedirect("login.jsp");
                }
                //Getting parameters
                String changeName = request.getParameter("name");
                String changePass = request.getParameter("pass");
                String back = request.getParameter("back");
                if (changeName != null) {
                    //Checking if valid values are entered
                    String nameSur = request.getParameter("nameSur");
                    boolean valnameSur = false;
            
      out.write("\n");
      out.write("            <form action=\"editDetails.jsp\" method=\"post\"> <br>\n");
      out.write("                <div class=\"headers\">Name and Surname (display name):</div> <br>\n");
      out.write("                    ");

                        //Ckecking if valid name and surname entered
                        if (nameSur.matches("^[A-z\\s]{3,}$")) {
                            valnameSur = true;
                            out.println("<input type='text' name='nameSur' "
                                    + "value='" + nameSur + "' placeholder='3-25 characters'"
                                    + " class='in-correct'> <br>");
                        } else {
                            out.println("<input type='text' name='nameSur' "
                                    + "value='" + nameSur + "' placeholder='3-25 characters'"
                                    + " class='in-wrong'> <br>");
                        }
                    
      out.write("\n");
      out.write("                <div class=\"headers\">Current password:</div> <br>\n");
      out.write("                <input type=\"password\" name=\"curPass\"> <br>\n");
      out.write("                ");

                    if (valnameSur) {
                        String curPass = request.getParameter("curPass");
                        connection.start();
                        //Checking if password is correct
                        connection.executeQuery("SELECT nameAndSur FROM users "
                                + "WHERE pass = '" + curPass + 
                                "' AND nameAndSur = '" + name + "'");
                        if (connection.next()) {
                            connection.reset();
                            //Changing name and surname
                            int re = connection.executeUpdate("UPDATE users "
                                    + "SET nameAndSur = " + nameSur 
                                    + " WHERE nameAndSur = " + name);
                            if (re == 0) {
                                out.println("<red>An error occured, "
                                        + "change name unsuccessfull!</red>");
                            } else {
                                out.println("<green>Changed name successfully.</green>");
                                name = nameSur;
                            }
                        } else {
                            out.println("<red>Wrong password!</red>");
                        }
                    } else {
                        out.println("<red>Please input Name and Surname.</red>");
                    }
                
      out.write("\n");
      out.write("                <br> <input type=\"submit\" value=\"Change Name\" name=\"name\" class=\"btn-name\">\n");
      out.write("            </form>\n");
      out.write("            ");

            } else {
            
      out.write("\n");
      out.write("            <form action=\"editDetails.jsp\" method=\"post\"> <br>\n");
      out.write("                <div class=\"headers\">Name and Surname (display name):</div> <br>\n");
      out.write("                <input type=\"text\" name=\"nameSur\" placeholder=\"3-25 characters\"\n");
      out.write("                       class=\"in-correct\"> <br>\n");
      out.write("                <div class=\"headers\">Current password:</div> <br>\n");
      out.write("                <input type=\"password\" name=\"curPass\" class=\"in-correct\"> <br> <br>\n");
      out.write("                <input type=\"submit\" value=\"Change Name\" name=\"name\" class=\"btn-name\">\n");
      out.write("            </form>\n");
      out.write("            ");
                }
                if (changePass != null) {
                    //Getting parameters
                    String pass1 = request.getParameter("pass1");
                    String pass2 = request.getParameter("pass2");
                    boolean valPass = false;
                    boolean valRe = false;
                    String message = "";
            
      out.write("\n");
      out.write("            <br> <br>\n");
      out.write("            <form action=\"editDetails.jsp\" method=\"post\">\n");
      out.write("                <div class=\"headers\">New Password:</div> <br>\n");
      out.write("                    ");

                        //Checking if valid password entered
                        if (pass1.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])"
                                + "(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
                            valPass = true;
                            out.println("<input type='password' name='pass1'"
                                    + " placeholder='8-15, 1 number, 1 upper and lowercase'"
                                    + " class='in-correct'> <br>");
                        } else {
                            out.println("<input type='password' name='pass1'"
                                    + " placeholder='8-15, 1 number, 1 upper and lowercase'"
                                    + " class='in-wrong'> <br>");
                            message = "Please input valid password.";
                        }
                    
      out.write("\n");
      out.write("                <div class=\"headers\">Re-enter password:</div> <br>\n");
      out.write("                    ");

                        //Checking if passwords match
                        if (valPass && pass1.equals(pass2)) {
                            valRe = true;
                            out.println("<input type='password' name='pass2'"
                                    + " class='in-correct'> <br>");
                        } else if (valPass) {
                            out.println("<input type='password' name='pass2'"
                                    + " class='in-wrong'> <br>");
                        } else {
                            out.println("<input type='password' name='pass2'"
                                    + " class='in-correct'> <br>");
                            if (message.isEmpty()) {
                                message = "Passwords don't match.";
                            }
                        }
                    
      out.write("\n");
      out.write("                <div class=\"headers\">Current password:</div> <br>\n");
      out.write("                <input type=\"password\" name=\"curPass\"> <br>\n");
      out.write("                ");

                    if (valPass && valRe) {
                        String curPass = request.getParameter("curPass");
                        //Checking if password is correct
                        connection.executeQuery("SELECT nameAndSur FROM users "
                                + "WHERE pass = '" + curPass 
                                + "' AND nameAndSur = '" + name + "'");
                        if (connection.next()) {
                            connection.reset();
                            //Changing password
                            int re = connection.executeUpdate("UPDATE users "
                                    + "SET password = " + pass1
                                    + " WHERE nameAndSur = " + name);
                            if (re == 0) {
                                out.println("<red>An error occured, "
                                        + "change password unsuccessfull!</red>");
                            } else {
                                out.println("<green>Change password successfull.</green>");
                            }
                        } else {
                            out.println("<red>Wrong password!</red>");
                        }
                    } else {
                        out.println("<red>" + message + "</red>");
                    }
                
      out.write("\n");
      out.write("                <br> <input type=\"submit\" value=\"Change Password\" name=\"pass\" class=\"btn-pass\">\n");
      out.write("            </form>\n");
      out.write("            ");


            } else {
            
      out.write("\n");
      out.write("            <br> <br>\n");
      out.write("            <form action=\"editDetails.jsp\" method=\"post\">\n");
      out.write("                <div class=\"headers\">New Password:</div> <br>\n");
      out.write("                <input type=\"password\" name=\"pass1\" placeholder=\"8-15, 1 number, \n");
      out.write("                       1 upper and lowercase\" class=\"in-correct\"> <br>\n");
      out.write("                <div class=\"headers\">Re-enter password:</div> <br>\n");
      out.write("                <input type=\"password\" name=\"pass2\" class=\"in-correct\"> <br>\n");
      out.write("                <div class=\"headers\">Current password:</div> <br>\n");
      out.write("                <input type=\"password\" name=\"curPass\" class=\"in-correct\"> <br> <br>\n");
      out.write("                <input type=\"submit\" value=\"Change Password\" name=\"pass\" class=\"btn-pass\">\n");
      out.write("            </form>\n");
      out.write("            ");
                }
                if (back != null) {
                    //Loading forum page
                    session.setAttribute("user", name);
                    response.sendRedirect("chat.jsp");
                }
            
      out.write("\n");
      out.write("            <form action=\"editDetails.jsp\" method=\"post\">\n");
      out.write("                <input type=\"submit\" value=\"Back to forum\" name=\"back\" class=\"btn-back\">\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
